### PR TITLE
Urgent fixes

### PR DESCRIPTION
**Pull request by hdsingh**
I have implemented the following:
1. Move `rasterize` to Style Panel
2. Use TextInput for `crs_params` and `proj_params`.

### CODE REVIEW

**Comment by martindurant** [comment]
> Use TextInput for crs_params and proj_params

Why this? You immediately do literal_eval anyway.

I meant that, instead of including `{'projection': crs.thing}` in your box, you can have `{'projection': 'thing'}`.

**Comment by hdsingh** [comment]
It seems from the failed test that we need to add `datashader` as a dependency. Earlier it was installed with `geoviews`. Or shall we make it optional like `metpy`?

**Comment by martindurant** [comment]
If rasterize is normally True, we need to include datashader explicitly. Otherwise, we would need to check for it and disable that option when it isn't present. I say add the dependency.

**Comment by hdsingh** [comment]
Now we can have 
```python
init_params = {'is_geo': True,
               'basemap': 'OSM',
               'crs params': "{'central_longitude': 0,  'globe': {'ellipse':'sphere'}}"}       
```

**Comment by martindurant** [comment]
Yes, that's exactly how I think it should be. Merging this now (urgently!) to aid creation of content for presentation.

**Pull request merged**
