### PR TITLE
Various updates to improve look and feel

### PR DESCRIPTION
**Pull request by philippjfr**
- Uses WidgetBoxes to give rounded corners
- Uses margins appropriately
- Uses sizing mode to make GUI responsive to resizing

**Before**:

Screen Shot 2019-08-08 at 5 29 25 PM

**After**:

Screen Shot 2019-08-07 at 7 48 53 PM

**Before**:

Screen Shot 2019-08-08 at 5 27 45 PM

**After**:

Screen Shot 2019-08-07 at 7 49 01 PM

**Before**:

Screen Shot 2019-08-08 at 5 27 53 PM

**After**:

Screen Shot 2019-08-07 at 7 49 10 PM

**Before**:

Screen Shot 2019-08-08 at 5 28 01 PM

**After**:

Screen Shot 2019-08-07 at 7 49 17 PM

**Before**:

Screen Shot 2019-08-08 at 5 28 08 PM

**After**:

Screen Shot 2019-08-07 at 7 49 24 PM

### CODE REVIEW

**Comment by martindurant** [comment]
Would love the same treatment for dfviz :)

**Comment by jbednar** [comment]
Looks great! 

It would be nice to see the "before" pictures to see what's changed. 

Personally, I'd vote to update the styling for tables so that the greyed rows are only subtly greyer than the non-grey ones; I think they should be clearly distinct colors but shouldn't come across like a zebra pattern, which is both visually jarring and also makes it more difficult to read black text.

**Comment by philippjfr** [comment]
Updated with before/after screenshots.

**Comment by philippjfr** [comment]
Debating whether to reverse the decision to fill the whole width of the screen since most of it is empty anyway.

**Comment by jbednar** [comment]
Seems subtle, but I don't spot anything that looks worse!

**Comment by martindurant** [comment]
I'll fix the conflict when I have a spare few minutes.

**Comment by martindurant** [comment]
I don't seem to be able to push here, so made https://github.com/philippjfr/xrviz/pull/1

**Comment by rsignell-usgs** [comment]
@martindurant is this in your court?

**Comment by martindurant** [comment]
The PR conflict needs resolution, but I don't seem to be able to push here. @philippjfr ?

**Comment by philippjfr** [comment]
I'll fix shortly. Also working on intake integration tonight.

**Comment by philippjfr** [comment]
Okay, done.

**Comment by martindurant** [comment]
Excellent. I will be responding only slowly to messages from now for a couple of weeks.

**Pull request merged**
