### PR TITLE
Changing style to have vertical tabs

### PR DESCRIPTION
**Pull request by jsignell**
This PR changes the orientation of the tabs and does other small changes to reduce the vertical space taken up by the control panel.

## Before ________________________________________________________ After

Screen Shot 2019-10-21 at 2 13 08 PMScreen Shot 2019-10-21 at 2 17 10 PM

## New control panes
Screen Shot 2019-10-18 at 9 40 43 AM
Screen Shot 2019-10-18 at 9 40 50 AM
Screen Shot 2019-10-18 at 9 40 59 AM
Screen Shot 2019-10-18 at 9 41 11 AM
Screen Shot 2019-10-18 at 9 41 22 AM

### CODE REVIEW

**Comment by hdsingh** [comment]
This new orientation looks much better as well as saves vertical space. I just made minor changes in the tests.

**Comment by martindurant** [comment]
Did you not intend to put the plot into a tab too, so it renders when the tab is clicked, instead of the "plot" button?

**Comment by jsignell** [comment]
I ended up changing my mind on that one. @rsignell-usgs was strong opposed.

**Comment by martindurant** [comment]
Thank you! 
Also for `dfviz` :)

**Pull request merged**
