### PR TITLE
Using new xarray html repr for describe

### PR DESCRIPTION
**Pull request by jsignell**
This is for when xarray 0.14.1 is released (which will be soon). 

Screen Shot 2019-10-25 at 1 32 38 PM

### CODE REVIEW

**Comment by jsignell** [comment]
I'm still thinking about how to make the repr itself something that the user can select on. So that there doesn't have to be duplicated lists.

**Comment by martindurant** [comment]
If showing the repr, then the choice really can be from the simpler combo box, which only shows one clickable label.
Will this break your vertical space requirements?

**Comment by jsignell** [comment]
> If showing the repr, then the choice really can be from the simpler combo box, which only shows one clickable label.

Or it could even be an autocomplete input. Which feels even more usable to me.

> Will this break your vertical space requirements?

I gave the repr a max_height and scroll on overflow, so it'll never get too big.

**Comment by martindurant** [comment]
> it could even be an autocomplete input 

Would love to see it, if you know how.

**Comment by jsignell** [comment]
Unfortunately it wasn't exposed yet to allow autocompletion even for 1 character. I opened the PR on panel. https://github.com/pyviz/panel/pull/721

**Comment by jsignell** [comment]
Ok now that xarray and panel have been released, I'm going to clean up any tests and merge this PR.

**Comment by martindurant** [comment]
hurray!

**Pull request merged**
