### PR TITLE
unpin holoviews

### PR DESCRIPTION
**Pull request by jhamman**
closes #45 

(holoviews 1.12.6 was released 4 days ago)

cc @rsignell-usgs

### CODE REVIEW

**Comment by martindurant** [comment]
Good with me, but I'll wait for @rsignell-usgs 's sign-off, since I wasn't following closely.

**Comment by hdsingh** [comment]
I have tested xrviz using the latest packages with this environment file:
```
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - xarray
  - netcdf4
  - datashader
  - holoviews
  - geoviews
  - hvplot
  - panel
```
Results: Two tests are failing, due to selectors not appearing in case of (`lat`, `lon`) as (x,y).
Present packages (holoviews==1.12.1) (Selectors are available):

Screenshot from 2019-10-14 07-17-42

Latest packages  (Selectors are *not* available):
Screenshot from 2019-10-14 07-17-59

@jhamman Are you also encountering the same behaviour?

**Comment by jhamman** [comment]
My main problem right now is that I can't put xrviz into Pangeo's production environment because holoviews has its version fixed at v1.12.1.

Given that the upstream fixes didn't seem to fix the problems here, perhaps xrviz is in need of some updates?

**Comment by hdsingh** [comment]
I am trying to figure out why tests are passing  in [job 2](https://travis-ci.org/intake/xrviz/jobs/597605742#L367) but failing in [job 1](https://travis-ci.org/intake/xrviz/jobs/597605741#L692).

All the tests pass for me locally created using the above mentioned [env file](https://github.com/intake/xrviz/pull/48#issuecomment-541483267) and I have reconfirmed this by creating env again. 

It also fails for `conda install  xarray cartopy panel hvplot netcdf4 datashader`. I am trying to figure out the reason behind inconsistency in packages (having same hv version) using two different methods (env file vs command)

**Comment by martindurant** [comment]
You maybe want to add `conda list --explicit` into the build script, so you know exactly what package/channel/builds you are working with.

**Comment by hdsingh** [comment]
I explained this inconsistency in a comment in [gitter](https://gitter.im/ESIP_GUI/community).

**Comment by martindurant** [comment]
It would be better to keep the discussion on github, which is more easily searched by outsiders.

So it seems, things work with the conda-forge version, which is where xrviz is too, so I would accept unpinning and close the issue. Maybe @philippjfr can comment on the different versions (although it's unlikely to be hvplot, maybe bokeh or something else).

**Comment by jhamman** [comment]
Thanks folks! Can we also ask for a new release of xrviz too?

**Comment by hdsingh** [comment]
I made a release on PyPi. Latest conda-forge version would also be available soon.

**Comment by philippjfr** [comment]
The difference you describe is simply down to different Panel versions I think. I've seen a number of issues with xrviz I've been meaning to look at, I know @jsignell started fixing some issues but focused on getting hvplot released first.

**Pull request merged**
