### PR TITLE
Revert "unpin holoviews"

### PR DESCRIPTION
**Pull request by rsignell-usgs**
Reverts intake/xrviz#45

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@jhamman I merged because yes, you no longer need to pin holoviews, but then realized you need to do something like:
```
  - pyviz/label/dev::hvplot
  - pyviz/label/dev::holoviews
  - pyviz/label/dev::panel
  - pyviz/label/dev::datashader
  - metpy
  - numpy
  - xarray
  - pip
  - pip:
    - git+https://github.com/pyviz/geoviews.git
```
to get the tooltips to accurately show lon/lat.

**Comment by jhamman** [comment]
Ugh! This is too bad. xrviz is basically unusable in its current state. A package this small shouldn't be pinning a widely used dependency like this. My preference would be forgo tool tips today and push holoviews to make a release ASAP. Thoughts?

**Comment by rsignell-usgs** [comment]
@jhamman, indeed, this is a sad state of affairs.  Hopefully things will change : https://github.com/pyviz/hvplot/issues/324

My preference would be to use the dev channels and geoviews master for now:
```
 channels:
  - conda-forge
dependencies:
  - cartopy
  - fsspec
  - pyviz/label/dev::hvplot
  - pyviz/label/dev::holoviews
  - pyviz/label/dev::panel
  - pyviz/label/dev::datashader
  - metpy
  - numpy
  - xarray
  - pip
  - pip:
    - git+https://github.com/pyviz/geoviews.git
```
and then switch to conda-forge when the next release is made, after which @philippjfr says things should calm down for a while.

**Comment by philippjfr** [comment]
Will try my best to release datashader, holoviews and panel today. @jsignell probably has a better handle on how far out an hvPlot release is.

**Comment by jhamman** [comment]
Thanks @philippjfr - those efforts will be much appreciated.

**Pull request merged**
